[versions]
# ANDROIDX
androidx-activity-compose = "1.8.2"
androidx-core-ktx = "1.12.0"
androidx-lifecycle-runtime = "2.7.0"

# COMPOSE
compose-bom = "2024.03.00"

# PLUGINS
android-gradle-plugin = "8.3.1"
kotlin-android = "1.9.23"

# PERMISSIONS
accompanist-permissions = "0.33.2-alpha"

# TEST
junit = "4.13.2"
test-ext = "1.1.5"
test-espresso-core = "3.5.1"

[libraries]
# ANDROIDX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }

# COMPOSE
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# PERMISSIONS
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permissions" }

# TEST
junit = { group = "junit", name = "junit", version.ref = "junit" }
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso-core" }
test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }

