[versions]
# ANDROIDX
androidx-activity-compose = "1.9.0"
androidx-core-ktx = "1.13.1"
androidx-lifecycle-runtime = "2.7.0"
lifecycle-viewmodel-compose = "2.7.0"

# AUTH
biometric = "1.2.0-alpha05"

# COMPOSE
compose-bom = "2024.05.00"

# KOIN
koin-android = "3.5.0"
koin-compose = "3.5.0"

# PERMISSIONS
accompanist-permissions = "0.33.2-alpha"

# PLUGINS
android-gradle-plugin = "8.3.2"
google-ksp = "1.9.22-1.0.17"
kotlin-android = "1.9.23"

# PREFERENCES
datastore-preferences = "1.1.1"

# ROOM
room = "2.6.1"

# TEST
junit = "4.13.2"
test-ext = "1.1.5"
test-espresso-core = "3.5.1"

[libraries]
# ANDROIDX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }

# AUTH
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }

# COMPOSE
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# KOIN
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin-compose" }

# PERMISSIONS
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permissions" }

# PREFERENCES
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }

# ROOM
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

# TEST
junit = { group = "junit", name = "junit", version.ref = "junit" }
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso-core" }
test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
